#!/bin/sh
ver=0.1
make clean
make distclean
if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi
/bin/rm -rf autom4te.cache .deps
if [ -d .git ] ; then
	mv .git ../gitlibqmail
fi
if [ -d RCS ] ; then
	mv RCS ../RCS"libqmail"
fi
if [ -d debian ] ; then
	mv debian ../debian"libqmail"
fi
cd ..
tar cf - libqmail-"$ver" |gzip -c > $rpmbuild/SOURCES/libqmail-"$ver".tar.gz
cd libqmail-"$ver"
if [ -d ../RCSlibqmail ] ; then
	mv ../RCSlibqmail ./RCS
fi
if [ -d ../debianlibqmail ] ; then
	mv ../debianlibqmail ./debian
fi
if [ -d ../gitlibqmail ] ; then
	mv ../gitlibqmail ./.git
fi
rpmbuild -bb libqmail
if test $# -eq 1
then
	#rpmbuild -bb --clean --target armv7hl airplay.spec
	rpmbuild -bb --clean --target $1 libqmail.spec
else
	rpmbuild -bb --clean libqmail.spec
fi
