#!/bin/sh
set -x
libqmail_version=$(cat conf-version)
/bin/rm -rf $HOME/stage/libqmail
mkdir -p $HOME/stage/libqmail-$libqmail_version

cp -rp . $HOME/stage/libqmail-$libqmail_version
make -s -C $HOME/stage/libqmail-$libqmail_version/debian
cd $HOME/stage/libqmail-$libqmail_version
dpkg-buildpackage -tc -b
ls -lt $HOME/stage
