#!/bin/sh
rcsflag=0
ver=0.1
make clean
make distclean
if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi
/bin/rm -rf autom4te.cache .deps
if test -d RCS
then
	rcsflag=1
	mv RCS ../RCS"libqmail"
fi
cd ..
tar cf - libqmail-"$ver" |gzip -c > $rpmbuild/SOURCES/libqmail-"$ver".tar.gz
cd libqmail-"$ver"
if test $rcsflag -eq 1
then
	mv ../RCSlibqmail ./RCS
fi
rpmbuild -bb libqmail
if test $# -eq 1
then
	#rpmbuild -bb --clean --target armv7hl airplay.spec
	rpmbuild -bb --clean --target $1 libqmail.spec
else
	rpmbuild -bb --clean libqmail.spec
fi
