.TH QGETPWENT 3  2021-07-05
.SH NAME
qgetpwent, qsetpwent, qendpwent \- get password file entry

.SH SYNOPSIS
.nf
.B #include <sys/types.h>
.B #include <qgetpwgr.h>
.PP
.B struct passwd *qgetpwent(void);
.PP
.B void qsetpwent(void);
.PP
.B void qendpwent(void);
.fi
.ad b
.SH DESCRIPTION
The
.BR qgetpwent ()
function returns a pointer to a structure containing
the broken-out fields of a record from the password database
(e.g., the local password file
.IR /etc/passwd ,
).
The first time
.BR qgetpwent ()
is called, it returns the first entry; thereafter, it returns successive
entries.
.PP
The
.BR qsetpwent ()
function rewinds to the beginning
of the password database.
.PP
The
.BR qendpwent ()
function is used to close the password database
after all processing has been performed.
.PP
The \fIpasswd\fP structure is defined in \fI<pwd.h>\fP as follows:
.PP
.in +4n
.EX
struct passwd {
    char   *pw_name;       /* username */
    char   *pw_passwd;     /* user password */
    uid_t   pw_uid;        /* user ID */
    gid_t   pw_gid;        /* group ID */
    char   *pw_gecos;      /* user information */
    char   *pw_dir;        /* home directory */
    char   *pw_shell;      /* shell program */
};
.EE
.in
.PP
For more information about the fields of this structure, see
.BR passwd (5).

.SH RETURN VALUE
The
.BR qgetpwent ()
function returns a pointer to a
.I passwd
structure, or NULL if
there are no more entries or an error occurred.
If an error occurs,
.I errno
is set appropriately.
If one wants to check
.I errno
after the call, it should be set to zero before the call.
.PP
The return value may point to a static area, and may be overwritten
by subsequent calls to
.BR qgetpwent (),
.BR qgetpwnam (3),
or
.BR qgetpwuid (3).
(Do not pass the returned pointer to
.BR free (3).)

.SH ERRORS
.TP
.B EINTR
A signal was caught; see
.BR signal (7).

.TP
.B ENOMEM
Insufficient memory to allocate
.I passwd
structure.

.TP
.B ERANGE
Insufficient buffer space supplied.

.TP
.B ETXTBUSY
Temporary error happened.

.SH FILES
.TP
.I /etc/passwd
local password database file

.SH SEE ALSO
.BR qgetpwent_r (3),
.BR qgetpwnam (3),
.BR qgetpwuid (3),
.BR passwd (5)
