.TH QGETGRENT_R 3 2021-07-05

.SH NAME
qgetgrent_r \- get group file entry reentrantly

.SH SYNOPSIS
.nf
.B #include <qgetpwgr.h>
.PP
.B int qgetgrent_r(struct group *gbuf, char *buf, size_t buflen, struct group **gbufp);
.fi
.PD
.ad b

.SH DESCRIPTION
The function \fBqgetgrent_r\fR() is the reentrant versions of
\fBqgetgrent\fR(3). It reads the next group entry from the stream
initialized by \fBqsetgrent\fR(3).
.PP
The \fIgroup\fR structure is defined in \fI<grp.h>\fR as follows:
.PP
.in +4n
.EX
struct group {
    char   *gr_name;        /* group name */
    char   *gr_passwd;      /* group password */
    gid_t   gr_gid;         /* group ID */
    char  **gr_mem;         /* NULL-terminated array of pointers
                               to names of group members */
};
.EE
.in
.PP
For more information about the fields of this structure, see
\fBgroup\fR(5).
.PP
The nonreentrant function return a pointer to static storage, where this
static storage contains further pointers to group name, password and
members. The reentrant function described here return all of that in
caller-provided buffers.
First of all there is the buffer \fIgbuf\fR that can hold a \fIstruct
group\fR. And next the buffer \fIbuf\fR of size \fIbuflen\fR that can hold
additional strings. The result of these functions, the \fIstruct group\fR
read from the stream, is stored in the provided buffer *\fIgbuf\fR, and a
pointer to this \fIstruct group\fR is returned in *\fIgbufp\fR.

.SH RETURN VALUE
On success, this function return 0 and *\fIgbufp\fR
is a pointer to the \fIstruct group\fR.
On error, these functions return an error value and
*\fIgbufp\fR is NULL.

.SH ERRORS
.TP
.B ENOENT
No more entries.

.TP
.B ERANGE
Insufficient buffer space supplied.
Try again with larger buffer.

.TP
.B ETXTBUSY
Temporary error happened.

.SH NOTES
The function \fBqgetgrent_r\fR() is not really reentrant since it shares
the reading position in the stream with all other threads.

.SH SEE ALSO
qgetgrent(3),
qgetgrnam(3),
qgetgrgid(3),
qgetgrnam_r(3),
qgetgrgid_r(3),
grpscan(3),
group(5)
