.TH CTIME 3 
.SH NAME
qtime - transform date and time to ASCII

.SH SYNOPSIS
.nf
.B #include <datetime.h>
.PP
char *\fBqtime\fR(\fBconst datetime_sec\fR \fIdts\fR);
.fi
.PP
.ad
.SH DESCRIPTION
The
.BR qtime (),
function take an argument of data type \fIdatetime_sec\fP, which
represents calendar time. When interpreted as an absolute time value, it
represents number of real-time seconds that have elapsed since the end of
1969 TAI.
.PP
\fBqtime\fR(\fIdts\fR)
converts the calendar time \fIt\fP into a
null-terminated string of the form
.PP
.in +4n
.EX
"Tue Jun 30 09:28:41 2021\en"
.EE
.in
.PP
The abbreviations for the days of the week are "Sun", "Mon", "Tue", "Wed",
"Thu", "Fri", and "Sat".
The abbreviations for the months are "Jan",
"Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", and
"Dec".
The return value points to a statically allocated string which
might be overwritten by subsequent calls to any of the date and time
functions.

.SH RETURN VALUE
On success,
.BR qtime ()
return a pointer to a string.

.SH SEE ALSO
date(1),
gettimeofday(2),
time(2),
utime(2),
clock(3),
difftime(3),
strftime(3),
strptime(3),
datetime(3),
caltime(3),
caltime_tai(3),
timegm(3),
tzset(3),
time(7)
