.TH setuserid 3
.SH NAME
setuserid \- set user identity
.SH SYNTAX
.B #include <setuserid.h>

int \fBsetuserid\fP(char* \fIuser\fR);
.SH DESCRIPTION

setuserid sets the effective user ID, effective group ID, supplementary groups of the
user \fIuser\fR from uid, gid, supplementary ids from passwd(5), group(5) database.
It uses setuid(2), setgid(2), setgroups, getpwnam(3), getgrent(3).

setuserid returns -1 on failure, 0 on success

.SH "SEE ALSO"
setuid(2),
setgid(2),
setgroups(2),
qgetpwnam(3),
qgetgrent(3),
grpscan(3),
setuser_privileges(3)
