.TH setuser_privileges 3
.SH NAME
setuser_privileges \- set user identity
.SH SYNTAX
.B #include <setuserid.h>

int \fBsetuser_privileges\fP(uid_t \fIuid\fR, gid_t \fIgid\fR, char* \fIuser\fR);
.SH DESCRIPTION

setuserid_privileges sets the effective user ID to \fIuid\fR, effective
group ID to \fIgid\fR, supplementary groups of the user \fIuser\fR to its
uid, gid obtained from passwd(5) and group(5) databases. It uses setuid(2),
setgid(2), setgroups(2), getpwnam(3), getgrent(3).

setuser_privileges returns -1 on failure, 0 on success

.SH "SEE ALSO"
setuid(2),
setgid(2),
setgroups(2),
qgetpwnam(3),
qgetgrent(3),
grpscan(3),
setuserid(3)
