name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Darwin
      run: if [ "${OS}" = "macos-latest" ]; then \
             brew install automake autoconf libtool pkgconfig openssl; \
             brew link --force openssl; \
             ln -s /usr/local/opt/openssl/include/openssl /usr/local/include; \
             fi
      env:
        OS: ${{ matrix.host }}

    - name: configure
      run: ./default.configure
    - name: make
      run: make
