name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: fedora-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure --prefix=/usr --mandir=/usr/share/man
    - name: make
      run: make
