name: libqmail Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**'
      - .github/workflows/libqmail-c-cpp.yml
      - '!**/debian/*'
      - '!**/libqmail.spec.in'
      - '!**/doc/*'
      - '!**.md'
      - '!**.3'
      - '!**/obs/*'
      - '!**/libqmail-freebsd.yml'
      - '!**/codeql.yml'
      - '!**/libqmail-obs.yml'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Darwin
      run: |
        if [ "${OS}" = "macos-latest" ]; then brew install automake autoconf libtool pkgconfig openssl; fi
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install gcc g++ automake autoconf libtool libssl-dev libsodium-dev; fi
      env:
        OS: ${{ matrix.host }}

    - name: configure
      run: env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.1/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.1/lib" ./default.configure
    - name: make
      run: env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.1/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.1/lib" make
