name: libqmail Ubuntu, Mac OSX CI

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - .github/workflows/libqmail-c-cpp.yml
      - '!**/libqmail/debian/*'
      - '!**/libqmail/doc/*'
      - '!**/libqmail/libqmail.spec.in'
      - '!**.md'
      - '!**/libqmail-freebsd.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Darwin
      run: if [ "${OS}" = "macos-latest" ]; then brew install automake autoconf libtool pkgconfig openssl; fi
      env:
        OS: ${{ matrix.host }}

    - name: configure
      run: env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./default.configure
    - name: make
      run: env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" make
    - name: prepare obs
      run: |
        if [ "${OS}" = "ubuntu-latest" ]; then ./prepare_obs libqmail; fi
      env:
        OS: ${{ matrix.host }}
    - uses: actions/upload-artifact@v2
      with:
        path: '~/*.gz'
        path: '~/*.spec'
