name: libqmail obs trigger

on:
  push:
    paths:
      - '**'
      - .github/workflows/libqmail-obs.yml
      - '!**/doc/*'
      - '!**.md'
      - '!**/libqmail-freebsd.yml'
      - '!**/libqmail-c-cpp.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_main
      uses: actions/checkout@v2

    - name: prepare obs
      run: |
        sudo apt-get update; sudo apt-get install libssl-dev libmysqlclient-dev
        ./prepare_obs libqmail
    - uses: actions/upload-artifact@v2
      with:
        name: libqmail
        path: ~/stage
    - shell: bash
      name: trigger_obs
      run: |
        mkdir ~/.ssh
        echo "${{secrets.sf_private_key}}" > ~/.private_key
        chmod 600 ~/.private_key
        echo "${{secrets.sf_known_hosts}}" > ~/.ssh/known_hosts
        cd ~/stage
        tar cvfz $GITHUB_WORKSPACE/libqmail-obs.tar.gz *
        # copy to /home/frs/project/indimail/github
        scp -q -i ~/.private_key $GITHUB_WORKSPACE/libqmail-obs.tar.gz  "${{secrets.sf_user}}:${{secrets.sf_upload_path}}"
        rm -f ~/.private_key ~/.ssh/known_hosts $GITHUB_WORKSPACE/libqmail-obs.tar.gz
        rm -rf ~/stage
