name: libqmail FreeBSD CI

on:
  push:
    paths:
      - '**'
      - .github/workflows/libqmail-freebsd.yml
      - '!**/debian/*'
      - '!**/libqmail.spec.in'
      - '!**/doc/*'
      - '!**.md'
      - '!**.3'
      - '!**/obs/*'
      - '!**/libqmail-c-cpp.yml'
      - '!**/libqmail-obs.yml'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: macos-12
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: install libqmail
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.2.1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf
        run: |
          ./default.configure
          make
