name: libqmail obs CI

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - .github/workflows/libqmail-c-cpp.yml
      - '!**/doc/*'
      - '!**.md'
      - '!**/libqmail-freebsd.yml'
      - '!**/libqmail-c-cpp.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_main
      uses: actions/checkout@v2

    - name: prepare obs
      run: ./prepare_obs libqmail
    - uses: actions/upload-artifact@v2
      with:
        name: libqmail
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
